const TeamNameMapping = {
  ARI: { name: "Arizona", id: 22 },
  ATL: { name: "Atlanta", id: 1 },
  BAL: { name: "Baltimore", id: 33 },
  BUF: { name: "Buffalo", id: 2 },
  CAR: { name: "Carolina", id: 29 },
  CHI: { name: "Chicago", id: 3 },
  CIN: { name: "Cincinnati", id: 4 },
  CLE: { name: "Cleveland", id: 5 },
  DAL: { name: "Dallas", id: 6 },
  DEN: { name: "Denver", id: 7 },
  DET: { name: "Detroit", id: 8 },
  GB: { name: "Green Bay", id: 9 },
  HOU: { name: "Houston", id: 34 },
  IND: { name: "Indianapolis", id: 11 },
  JAX: { name: "Jacksonville", id: 30 },
  KC: { name: "Kansas City", id: 12 },
  LAC: { name: "LA Chargers", id: 24 },
  LAR: { name: "LA Rams", id: 14 },
  LV: { name: "Las Vegas", id: 13 },
  MIA: { name: "Miami", id: 15 },
  MIN: { name: "Minnesota", id: 16 },
  NE: { name: "New England", id: 17 },
  NO: { name: "New Orleans", id: 18 },
  NYG: { name: "NY Giants", id: 19 },
  NYJ: { name: "NY Jets", id: 20 },
  PHI: { name: "Philadelphia", id: 21 },
  PIT: { name: "Pittsburgh", id: 23 },
  SEA: { name: "Seattle", id: 26 },
  SF: { name: "San Francisco", id: 25 },
  TB: { name: "Tampa Bay", id: 27 },
  TEN: { name: "Tennessee", id: 10 },
  WSH: { name: "Washington", id: 28 },
};

export default TeamNameMapping;
